# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\running_counts_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_running_counts_widget(object):
    def setupUi(self, running_counts_widget):
        running_counts_widget.setObjectName("running_counts_widget")
        running_counts_widget.resize(699, 320)
        self.running_counts_controls = QtWidgets.QFrame(running_counts_widget)
        self.running_counts_controls.setGeometry(QtCore.QRect(0, 0, 162, 311))
        self.running_counts_controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.running_counts_controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.running_counts_controls.setObjectName("running_counts_controls")
        self.running_counts_dwell_time_spin_box = QtWidgets.QDoubleSpinBox(self.running_counts_controls)
        self.running_counts_dwell_time_spin_box.setGeometry(QtCore.QRect(91, 40, 71, 22))
        self.running_counts_dwell_time_spin_box.setDecimals(4)
        self.running_counts_dwell_time_spin_box.setMinimum(0.0002)
        self.running_counts_dwell_time_spin_box.setMaximum(10000.0)
        self.running_counts_dwell_time_spin_box.setProperty("value", 5.0)
        self.running_counts_dwell_time_spin_box.setObjectName("running_counts_dwell_time_spin_box")
        self.running_counts_number_of_points = QtWidgets.QSpinBox(self.running_counts_controls)
        self.running_counts_number_of_points.setGeometry(QtCore.QRect(90, 10, 71, 22))
        self.running_counts_number_of_points.setMinimum(2)
        self.running_counts_number_of_points.setMaximum(100000)
        self.running_counts_number_of_points.setProperty("value", 200)
        self.running_counts_number_of_points.setDisplayIntegerBase(10)
        self.running_counts_number_of_points.setObjectName("running_counts_number_of_points")
        self.running_counts_push_button = QtWidgets.QPushButton(self.running_counts_controls)
        self.running_counts_push_button.setGeometry(QtCore.QRect(20, 240, 121, 51))
        self.running_counts_push_button.setObjectName("running_counts_push_button")
        self.label_18 = QtWidgets.QLabel(self.running_counts_controls)
        self.label_18.setGeometry(QtCore.QRect(40, 70, 51, 20))
        self.label_18.setObjectName("label_18")
        self.reset_running_counts_push_button = QtWidgets.QPushButton(self.running_counts_controls)
        self.reset_running_counts_push_button.setGeometry(QtCore.QRect(20, 200, 121, 31))
        self.reset_running_counts_push_button.setObjectName("reset_running_counts_push_button")
        self.label_8 = QtWidgets.QLabel(self.running_counts_controls)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 91, 20))
        self.label_8.setObjectName("label_8")
        self.running_counts_delay_spin_box = QtWidgets.QDoubleSpinBox(self.running_counts_controls)
        self.running_counts_delay_spin_box.setGeometry(QtCore.QRect(91, 70, 71, 22))
        self.running_counts_delay_spin_box.setDecimals(4)
        self.running_counts_delay_spin_box.setMinimum(0.05)
        self.running_counts_delay_spin_box.setMaximum(10000.0)
        self.running_counts_delay_spin_box.setSingleStep(0.05)
        self.running_counts_delay_spin_box.setProperty("value", 0.1)
        self.running_counts_delay_spin_box.setObjectName("running_counts_delay_spin_box")
        self.label_9 = QtWidgets.QLabel(self.running_counts_controls)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_9.setObjectName("label_9")
        self.running_counts_plot_frame = QtWidgets.QFrame(running_counts_widget)
        self.running_counts_plot_frame.setGeometry(QtCore.QRect(160, 50, 531, 261))
        self.running_counts_plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.running_counts_plot_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.running_counts_plot_frame.setObjectName("running_counts_plot_frame")
        self.running_counts_toolbar_frame = QtWidgets.QFrame(running_counts_widget)
        self.running_counts_toolbar_frame.setGeometry(QtCore.QRect(160, 0, 531, 51))
        self.running_counts_toolbar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.running_counts_toolbar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.running_counts_toolbar_frame.setObjectName("running_counts_toolbar_frame")

        self.retranslateUi(running_counts_widget)
        QtCore.QMetaObject.connectSlotsByName(running_counts_widget)

    def retranslateUi(self, running_counts_widget):
        _translate = QtCore.QCoreApplication.translate
        running_counts_widget.setWindowTitle(_translate("running_counts_widget", "Form"))
        self.running_counts_push_button.setText(_translate("running_counts_widget", "Run Counts"))
        self.label_18.setText(_translate("running_counts_widget", "Delay(s)"))
        self.reset_running_counts_push_button.setText(_translate("running_counts_widget", "Reset Counts"))
        self.label_8.setText(_translate("running_counts_widget", "Number of Points"))
        self.label_9.setText(_translate("running_counts_widget", "Dwell Time (ms)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    running_counts_widget = QtWidgets.QWidget()
    ui = Ui_running_counts_widget()
    ui.setupUi(running_counts_widget)
    running_counts_widget.show()
    sys.exit(app.exec_())
