# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\exporting_variables.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exporting_variables(object):
    def setupUi(self, exporting_variables):
        exporting_variables.setObjectName("exporting_variables")
        exporting_variables.resize(205, 338)
        exporting_variables.setMinimumSize(QtCore.QSize(205, 338))
        exporting_variables.setMaximumSize(QtCore.QSize(205, 338))
        self.single_variables_to_shelve = QtWidgets.QPlainTextEdit(exporting_variables)
        self.single_variables_to_shelve.setGeometry(QtCore.QRect(10, 20, 191, 121))
        self.single_variables_to_shelve.setMouseTracking(False)
        self.single_variables_to_shelve.setWhatsThis("")
        self.single_variables_to_shelve.setPlaceholderText("Variables to export. Comma seperated")
        self.single_variables_to_shelve.setObjectName("single_variables_to_shelve")
        self.label = QtWidgets.QLabel(exporting_variables)
        self.label.setGeometry(QtCore.QRect(10, 0, 141, 20))
        self.label.setObjectName("label")
        self.folder_location = QtWidgets.QLineEdit(exporting_variables)
        self.folder_location.setGeometry(QtCore.QRect(10, 170, 113, 20))
        self.folder_location.setReadOnly(True)
        self.folder_location.setPlaceholderText("")
        self.folder_location.setObjectName("folder_location")
        self.browse_button = QtWidgets.QPushButton(exporting_variables)
        self.browse_button.setGeometry(QtCore.QRect(130, 170, 75, 23))
        self.browse_button.setObjectName("browse_button")
        self.label_2 = QtWidgets.QLabel(exporting_variables)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_2.setObjectName("label_2")
        self.export_variables_push_button = QtWidgets.QPushButton(exporting_variables)
        self.export_variables_push_button.setGeometry(QtCore.QRect(10, 250, 191, 41))
        self.export_variables_push_button.setObjectName("export_variables_push_button")
        self.label_3 = QtWidgets.QLabel(exporting_variables)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 101, 16))
        self.label_3.setObjectName("label_3")
        self.file_name = QtWidgets.QLineEdit(exporting_variables)
        self.file_name.setGeometry(QtCore.QRect(10, 220, 113, 20))
        self.file_name.setPlaceholderText("")
        self.file_name.setObjectName("file_name")
        self.failure_text_label = QtWidgets.QLabel(exporting_variables)
        self.failure_text_label.setGeometry(QtCore.QRect(10, 300, 111, 16))
        self.failure_text_label.setStyleSheet("color:rgb(255, 0, 0)")
        self.failure_text_label.setObjectName("failure_text_label")

        self.retranslateUi(exporting_variables)
        QtCore.QMetaObject.connectSlotsByName(exporting_variables)

    def retranslateUi(self, exporting_variables):
        _translate = QtCore.QCoreApplication.translate
        exporting_variables.setWindowTitle(_translate("exporting_variables", "Export"))
        self.label.setText(_translate("exporting_variables", "Variables to Shelve:"))
        self.browse_button.setText(_translate("exporting_variables", "Browse"))
        self.label_2.setText(_translate("exporting_variables", "Folder Name"))
        self.export_variables_push_button.setText(_translate("exporting_variables", "Export"))
        self.label_3.setText(_translate("exporting_variables", "File Name(*db)"))
        self.file_name.setText(_translate("exporting_variables", "UI_ShelvedVariables"))
        self.failure_text_label.setText(_translate("exporting_variables", "Failure Text Label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    exporting_variables = QtWidgets.QWidget()
    ui = Ui_exporting_variables()
    ui.setupUi(exporting_variables)
    exporting_variables.show()
    sys.exit(app.exec_())
