# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_generator_qtpy.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignalGeneratorWindow(object):
    def setupUi(self, SignalGeneratorWindow):
        SignalGeneratorWindow.setObjectName("SignalGeneratorWindow")
        SignalGeneratorWindow.resize(230, 100)
        self.on_button = QtWidgets.QPushButton(SignalGeneratorWindow)
        self.on_button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.on_button.setObjectName("on_button")
        self.off_button = QtWidgets.QPushButton(SignalGeneratorWindow)
        self.off_button.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.off_button.setObjectName("off_button")
        self.label = QtWidgets.QLabel(SignalGeneratorWindow)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SignalGeneratorWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.frequency_entry = QtWidgets.QLineEdit(SignalGeneratorWindow)
        self.frequency_entry.setGeometry(QtCore.QRect(110, 40, 61, 20))
        self.frequency_entry.setObjectName("frequency_entry")
        self.power_entry = QtWidgets.QLineEdit(SignalGeneratorWindow)
        self.power_entry.setGeometry(QtCore.QRect(110, 70, 61, 20))
        self.power_entry.setObjectName("power_entry")
        self.set_frequency_button = QtWidgets.QPushButton(SignalGeneratorWindow)
        self.set_frequency_button.setGeometry(QtCore.QRect(180, 40, 41, 23))
        self.set_frequency_button.setObjectName("set_frequency_button")
        self.set_power_button = QtWidgets.QPushButton(SignalGeneratorWindow)
        self.set_power_button.setGeometry(QtCore.QRect(180, 70, 41, 23))
        self.set_power_button.setObjectName("set_power_button")

        self.retranslateUi(SignalGeneratorWindow)
        QtCore.QMetaObject.connectSlotsByName(SignalGeneratorWindow)

    def retranslateUi(self, SignalGeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        SignalGeneratorWindow.setWindowTitle(_translate("SignalGeneratorWindow", "Dialog"))
        self.on_button.setText(_translate("SignalGeneratorWindow", "Turn On"))
        self.off_button.setText(_translate("SignalGeneratorWindow", "Turn Off"))
        self.label.setText(_translate("SignalGeneratorWindow", "Frequency(MHz)"))
        self.label_2.setText(_translate("SignalGeneratorWindow", "Power (dBm)"))
        self.set_frequency_button.setText(_translate("SignalGeneratorWindow", "Set"))
        self.set_power_button.setText(_translate("SignalGeneratorWindow", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignalGeneratorWindow = QtWidgets.QDialog()
    ui = Ui_SignalGeneratorWindow()
    ui.setupUi(SignalGeneratorWindow)
    SignalGeneratorWindow.show()
    sys.exit(app.exec_())
