# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\aom_trigger_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AomTrigger(object):
    def setupUi(self, AomTrigger):
        AomTrigger.setObjectName("AomTrigger")
        AomTrigger.resize(144, 119)
        self.aom_trigger_frame = QtWidgets.QFrame(AomTrigger)
        self.aom_trigger_frame.setGeometry(QtCore.QRect(0, 0, 141, 111))
        self.aom_trigger_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aom_trigger_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aom_trigger_frame.setObjectName("aom_trigger_frame")
        self.toggle_aom_push_button = QtWidgets.QPushButton(self.aom_trigger_frame)
        self.toggle_aom_push_button.setGeometry(QtCore.QRect(4, 2, 131, 71))
        self.toggle_aom_push_button.setObjectName("toggle_aom_push_button")
        self.label = QtWidgets.QLabel(self.aom_trigger_frame)
        self.label.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label.setObjectName("label")
        self.aom_power_entry = QtWidgets.QLineEdit(self.aom_trigger_frame)
        self.aom_power_entry.setGeometry(QtCore.QRect(70, 80, 61, 20))
        self.aom_power_entry.setText("")
        self.aom_power_entry.setMaxLength(8)
        self.aom_power_entry.setReadOnly(True)
        self.aom_power_entry.setObjectName("aom_power_entry")

        self.retranslateUi(AomTrigger)
        QtCore.QMetaObject.connectSlotsByName(AomTrigger)

    def retranslateUi(self, AomTrigger):
        _translate = QtCore.QCoreApplication.translate
        AomTrigger.setWindowTitle(_translate("AomTrigger", "Form"))
        self.toggle_aom_push_button.setText(_translate("AomTrigger", "Turn On Aom"))
        self.label.setText(_translate("AomTrigger", "Power(mW):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AomTrigger = QtWidgets.QWidget()
    ui = Ui_AomTrigger()
    ui.setupUi(AomTrigger)
    AomTrigger.show()
    sys.exit(app.exec_())
