# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pulse_generator_device_trigger_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pulse_generator_device_trigger_widget(object):
    def setupUi(self, pulse_generator_device_trigger_widget):
        pulse_generator_device_trigger_widget.setObjectName("pulse_generator_device_trigger_widget")
        pulse_generator_device_trigger_widget.resize(144, 119)
        self.aom_trigger_frame = QtWidgets.QFrame(pulse_generator_device_trigger_widget)
        self.aom_trigger_frame.setGeometry(QtCore.QRect(0, 0, 141, 111))
        self.aom_trigger_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aom_trigger_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aom_trigger_frame.setObjectName("aom_trigger_frame")
        self.toggle_push_button = QtWidgets.QPushButton(self.aom_trigger_frame)
        self.toggle_push_button.setGeometry(QtCore.QRect(4, 2, 131, 71))
        self.toggle_push_button.setObjectName("toggle_push_button")
        self.label = QtWidgets.QLabel(self.aom_trigger_frame)
        self.label.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label.setObjectName("label")
        self.power_entry = QtWidgets.QLineEdit(self.aom_trigger_frame)
        self.power_entry.setGeometry(QtCore.QRect(70, 80, 61, 20))
        self.power_entry.setText("")
        self.power_entry.setMaxLength(8)
        self.power_entry.setReadOnly(True)
        self.power_entry.setObjectName("power_entry")

        self.retranslateUi(pulse_generator_device_trigger_widget)
        QtCore.QMetaObject.connectSlotsByName(pulse_generator_device_trigger_widget)

    def retranslateUi(self, pulse_generator_device_trigger_widget):
        _translate = QtCore.QCoreApplication.translate
        pulse_generator_device_trigger_widget.setWindowTitle(_translate("pulse_generator_device_trigger_widget", "Form"))
        self.toggle_push_button.setText(_translate("pulse_generator_device_trigger_widget", "Turn On"))
        self.label.setText(_translate("pulse_generator_device_trigger_widget", "Power(mW):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pulse_generator_device_trigger_widget = QtWidgets.QWidget()
    ui = Ui_pulse_generator_device_trigger_widget()
    ui.setupUi(pulse_generator_device_trigger_widget)
    pulse_generator_device_trigger_widget.show()
    sys.exit(app.exec_())
