# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\image_scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.side_bar_frame = QtWidgets.QFrame(self.centralwidget)
        self.side_bar_frame.setGeometry(QtCore.QRect(730, 0, 301, 821))
        self.side_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar_frame.setObjectName("side_bar_frame")
        self.main_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tabs.setGeometry(QtCore.QRect(0, 0, 731, 821))
        self.main_tabs.setObjectName("main_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.image_scan_widget_frame = QtWidgets.QFrame(self.tab)
        self.image_scan_widget_frame.setGeometry(QtCore.QRect(0, 0, 721, 431))
        self.image_scan_widget_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_scan_widget_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_scan_widget_frame.setObjectName("image_scan_widget_frame")
        self.debug_graphs_tabs = QtWidgets.QTabWidget(self.tab)
        self.debug_graphs_tabs.setGeometry(QtCore.QRect(0, 430, 721, 341))
        self.debug_graphs_tabs.setObjectName("debug_graphs_tabs")
        self.z_scan_tab = QtWidgets.QWidget()
        self.z_scan_tab.setObjectName("z_scan_tab")
        self.debug_graphs_tabs.addTab(self.z_scan_tab, "")
        self.running_counts_tab = QtWidgets.QWidget()
        self.running_counts_tab.setObjectName("running_counts_tab")
        self.debug_graphs_tabs.addTab(self.running_counts_tab, "")
        self.main_tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.main_tabs.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tabs.setCurrentIndex(0)
        self.debug_graphs_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.debug_graphs_tabs.setTabText(self.debug_graphs_tabs.indexOf(self.z_scan_tab), _translate("MainWindow", "Z Scan"))
        self.debug_graphs_tabs.setTabText(self.debug_graphs_tabs.indexOf(self.running_counts_tab), _translate("MainWindow", "Running Counts"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab), _translate("MainWindow", "Image Scan"))
        self.main_tabs.setTabText(self.main_tabs.indexOf(self.tab_2), _translate("MainWindow", "ESR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
